@startuml

' definitions
abstract class Entity {
    id: int

    + Entity(id: int)
}

abstract class ValueObject<T> {
    value: T

    + ValueObject(value: T)
    - Validate(value: T)
}

enum OffenseType {
    TaxEvasion
    IncomeConcealer
}

enum EvasionCountry {
    France
    Germany
    ...
}

enum ResponseType {
    Confirmation
    Reject
}

enum PersonType {
    Suspect
    Informant
    Calamar
}


' relation
Entity <|-- Person
Entity <|-- Reponse
Entity <|-- Denunciation

ValueObject <|-- Offense

PersonType <|-- Person

Offense <-- Denunciation
OffenseType <- Offense

EvasionCountry "0..1" <-- Denunciation
ResponseType <-- Reponse

@enduml