// <auto-generated />
using System;
using JeBalance.Architecture.SQLite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JeBalance.Architecture.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240105170003_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.25");

            modelBuilder.Entity("JeBalance.Architecture.SQLite.Model.DenonciationSQLite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("Horodatage")
                        .HasColumnType("TEXT")
                        .HasColumnName("horodatage");

                    b.Property<int>("IdInformateur")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_informateur");

                    b.Property<int?>("IdReponse")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_reponse");

                    b.Property<int>("IdSuspect")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_suspect");

                    b.Property<string>("PaysEvasion")
                        .HasColumnType("TEXT")
                        .HasColumnName("pays_evasion");

                    b.Property<int>("Statut")
                        .HasColumnType("int")
                        .HasColumnName("statut");

                    b.Property<int>("TypeDelit")
                        .HasColumnType("int")
                        .HasColumnName("type_delit");

                    b.HasKey("Id");

                    b.ToTable("DENONCIATIONS", "app");
                });

            modelBuilder.Entity("JeBalance.Architecture.SQLite.Model.InformateurSQLite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nom");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("prenom");

                    b.HasKey("Id");

                    b.ToTable("INFORMATEURS", "app");
                });
#pragma warning restore 612, 618
        }
    }
}
